### PR TITLE
Feature/config imports

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by rwjblue** [comment]
Made this PR from @andyhot's feature branch mentioned in https://github.com/rwjblue/ember-module-migrator/issues/48.

**Comment by iezer** [comment]
👍  On this, I just came across this use case. Thanks a lot @andyhot. I also found a a couple of similar cases where files have moved into `src` so the paths have to be updated:

 - In `tests/helpers/resolver.js` needs to change from `import Resolver from '../../resolver';` to `import Resolver from '../../src/resolver';`.

 - In 'tests/start-app.js`, `import Application from '../../app';` has to change to `import Application from '../../src/main';`

There are examples in [this commit](https://github.com/201-created/travis-web/commit/ebc696e9d147942b94273a7a3dd172b67f9708b2)

@andyhot do you have to time to add handlers for those files? If not I can try to find time later today.

**Comment by andyhot** [comment]
@iezer Can you augment the https://github.com/andyhot/ember-module-migrator/tree/feature/config-imports/test/fixtures/config (or perhaps https://github.com/rwjblue/ember-module-migrator/tree/master/test/fixtures/classic-relative-imports since what you're reporting doesn't seem relatedto the config handling) with some failures? Those imports from tests sources should have been working (since https://github.com/rwjblue/ember-module-migrator/commit/9db3d972a167404b4f27a9502395cb8c19909563) but i guess they need some finetuning

**Comment by iezer** [comment]
@andyhot Yep I'll write some tests for those cases.

**Pull request merged**
